### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by woter1832** [onixpro/mkdocs-drawio-file#14]
I might be doing something wrong, but I am unable to build MKDocs with this plugin enabled in `mkdocs.yml`

#### Error message from GitHub Actions pipeline with plugin enabled:
```
Run poetry run mkdocs build
  poetry run mkdocs build
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.11.5/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.11.5/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.5/x64
    Python[2](https://github.com/rax-rccc/rcz-docs/actions/runs/6424519577/job/17445317256#step:7:2)_ROOT_DIR: /opt/hostedtoolcache/Python/[3](https://github.com/rax-rccc/rcz-docs/actions/runs/6424519577/job/17445317256#step:7:3).11.5/x6[4](https://github.com/rax-rccc/rcz-docs/actions/runs/6424519577/job/17445317256#step:7:4)
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.[5](https://github.com/rax-rccc/rcz-docs/actions/runs/6424519577/job/17445317256#step:7:5)/x[6](https://github.com/rax-rccc/rcz-docs/actions/runs/6424519577/job/17445317256#step:7:6)4
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.5/x64/lib
INFO    -  DeprecationWarning: invalid escape sequence '\&'
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/runner/.cache/pypoetry/virtualenvs/az-static-web-app-docs-template-4qalQBe--py3.11/lib/python3.11/site-packages/mkdocs_drawio_file/plugin.py", line 9[7](https://github.com/rax-rccc/rcz-docs/actions/runs/6424519577/job/17445317256#step:7:7), in 
    str_xml = str_xml.replace("\"", "\&quot;")

INFO    -  MERMAID2  - Initialization arguments: {}
INFO    -  MERMAID2  - Using javascript library (10.4.0):
   https://unpkg.com/mermaid@10.4.0/dist/mermaid.esm.min.mjs
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: /home/runner/work/rcz-docs/rcz-docs/build
ERROR   -  Error building page 'enterprise-scale/enterprise-scale-intro.md': list index out of range
Traceback (most recent call last):
  File "/home/runner/.cache/pypoetry/virtualenvs/az-static-web-app-docs-template-4qalQBe--py3.11/bin/mkdocs", line [8](https://github.com/rax-rccc/rcz-docs/actions/runs/6424519577/job/17445317256#step:7:8), in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/az-static-web-app-docs-template-4qalQBe--py3.11/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/az-static-web-app-docs-template-4qalQBe--py3.11/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/az-static-web-app-docs-template-4qalQBe--py3.11/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/az-static-web-app-docs-template-4qalQBe--py3.11/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
Warning: Found 0 results for page name 'Demo Drawio diagram'
Warning: Found 0 results for page name ''
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/az-static-web-app-docs-template-4qalQBe--py3.11/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/az-static-web-app-docs-template-4qalQBe--py3.11/lib/python3.11/site-packages/mkdocs/__main__.py", line 286, in build_command
    build.build(cfg, dirty=not clean)
  File "/home/runner/.cache/pypoetry/virtualenvs/az-static-web-app-docs-template-4qalQBe--py3.11/lib/python3.11/site-packages/mkdocs/commands/build.py", line 34[9](https://github.com/rax-rccc/rcz-docs/actions/runs/6424519577/job/17445317256#step:7:9), in build
    _build_page(
  File "/home/runner/.cache/pypoetry/virtualenvs/az-static-web-app-docs-template-4qalQBe--py3.[11](https://github.com/rax-rccc/rcz-docs/actions/runs/6424519577/job/17445317256#step:7:12)/lib/python3.11/site-packages/mkdocs/commands/build.py", line [23](https://github.com/rax-rccc/rcz-docs/actions/runs/6424519577/job/17445317256#step:7:24)5, in _build_page
    output = config.plugins.on_post_page(output, page=page, config=config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/az-static-web-app-docs-template-4qalQBe--py3.11/lib/python3.11/site-packages/mkdocs/plugins.py", line 586, in on_post_page
    return self.run_event('post_page', output, page=page, config=config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/az-static-web-app-docs-template-4qalQBe--py3.11/lib/python3.11/site-packages/mkdocs/plugins.py", line [50](https://github.com/rax-rccc/rcz-docs/actions/runs/6424519577/job/17445317256#step:7:51)7, in run_event
    result = method(item, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/az-static-web-app-docs-template-4qalQBe--py3.11/lib/python3.11/site-packages/mkdocs_drawio_file/plugin.py", line [56](https://github.com/rax-rccc/rcz-docs/actions/runs/6424519577/job/17445317256#step:7:57), in on_post_page
    diagram.replace_with(BeautifulSoup(self.substitute_image(path, diagram['src'], diagram['alt']), 'html.parser'))
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/az-static-web-app-docs-template-4qalQBe--py3.11/lib/python3.11/site-packages/mkdocs_drawio_file/plugin.py", line [65](https://github.com/rax-rccc/rcz-docs/actions/runs/6424519577/job/17445317256#step:7:66), in substitute_image
    diagram = self.parse_diagram(diagram_xml, alt)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/.cache/pypoetry/virtualenvs/az-static-web-app-docs-template-4qalQBe--py3.11/lib/python3.11/site-packages/mkdocs_drawio_file/plugin.py", line 74, in parse_diagram
    mxfile = data.xpath("//mxfile")[0]
             ~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
Error: Process completed with exit code 1.
```

#### Same stage of pipeline with the plugin disabled:
```
Run poetry run mkdocs build
  poetry run mkdocs build
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.11.5/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.11.5/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.5/x64
    Python[2](https://github.com/rax-rccc/rcz-docs/actions/runs/6425030073/job/17446862179#step:7:2)_ROOT_DIR: /opt/hostedtoolcache/Python/[3](https://github.com/rax-rccc/rcz-docs/actions/runs/6425030073/job/17446862179#step:7:3).11.5/x6[4](https://github.com/rax-rccc/rcz-docs/actions/runs/6425030073/job/17446862179#step:7:4)
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.[5](https://github.com/rax-rccc/rcz-docs/actions/runs/6425030073/job/17446862179#step:7:5)/x[6](https://github.com/rax-rccc/rcz-docs/actions/runs/6425030073/job/17446862179#step:7:6)4
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.5/x64/lib
INFO    -  MERMAID2  - Initialization arguments: {}
INFO    -  MERMAID2  - Using javascript library (10.4.0):
   https://unpkg.com/mermaid@10.4.0/dist/mermaid.esm.min.mjs
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: /home/runner/work/rcz-docs/rcz-docs/build
INFO    -  Number headings up to level 3.
INFO    -  Generate a table of contents up to heading level 2.
INFO    -  Generate a cover page with "default_cover.html.j2".
INFO    -  Converting <img> alignment(workaround).
INFO    -  Rendering for PDF.
INFO    -  Output a PDF to "/home/runner/work/rcz-docs/rcz-docs/build/pdf/document.pdf".
INFO    -  Converting 28 articles to PDF took 13.5s
INFO    -  Documentation built in 14.[7](https://github.com/rax-rccc/rcz-docs/actions/runs/6425030073/job/17446862179#step:7:7)[9](https://github.com/rax-rccc/rcz-docs/actions/runs/6425030073/job/17446862179#step:7:9) seconds
```

The plugin is installed with Poetry (`pyproject.toml`):

```
[tool.poetry]
name = "az-static-web-app-docs-template"
version = "1.6.1"
description = ""
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
mkdocs = "^1.5.3"
mkdocs-material = "^9.4.4"
mkdocs-git-revision-date-plugin = "^0.3.2"
mkdocs-macros-plugin = "^1.0.4"
mkdocs-mermaid2-plugin = "^1.1.1"
mkdocs-with-pdf = "^0.9.3"
#mkdocs-drawio-exporter = "^0.8.0"
mkdocs-glightbox = "^0.3.4"
mkdocs-drawio-file = "^1.5.2"

[tool.poetry.dev-dependencies]
isort = "^5.10.1"
black = "^22.6.0"
mypy = "^0.971"
flake8 = "^6.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

The `poetry.lock` file has been updated using the command `poetry lock --no-update`

The file mentioned in the line `Error building page 'enterprise-scale/enterprise-scale-intro.md': list index out of range` looks like:
```
# Introduction

## Overview

![](assets/png/es-tf-overview.png)

---

![](assets/svg/es-tf.drawio.svg)

## Service connections

![](assets/svg/es-tf-service-connections.drawio.svg)

## State infrastructure
![](assets/svg/es-tf-state-infrastructure.drawio.svg)
```

I realise none of the images are `.drawio` files, but if I remove this file, another one will show in the error, regardless of whether it has images or not.

Am I doing something wrong or is this a bug?

Thank you in advance.

**Comment by FalkonEon** [comment]
The Problem is you use *.drawio.svg. We have the same problem.
You can only use *.drawio

**Comment by mattmeye** [comment]
Would you accept a pull request? @tuunit

**Comment by tuunit** [comment]
> Would you accept a pull request? [@tuunit](https://github.com/tuunit)

Any time, but this repo is abandoned. 

I've created a fork 1,5 years ago and it has been updated, bugs squashed and new features have been added as well

https://github.com/tuunit/mkdocs-drawio
